linters:
  disable-all: true
  enable:
    - goimports
    - gocyclo
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
      #- golint
    - misspell
    - staticcheck
issues:
  exclude-use-default: false
run:
  deadline: 5m
