version: '3.8'
services:
  jaeger:
    network_mode: "bridge"
    image: jaegertracing/all-in-one:1.8 
    # XXX uncomment if you need to debug your jaeger setup
    #command: --log-level debug
    ports:
      - 16686:16686
  tinyci:
    network_mode: "bridge"
    image: tinyci-agents
    command: make start-services
    init: true
    working_dir: "/go/src/github.com/tinyci/ci-agents"
    ports:
      - 3000:3000
      - 6000:6000
      - 6001:6001
      - 6002:6002
      - 6005:6005
      - 6010:6010
    environment:
      - "JAEGER_AGENT_HOST=jaeger"
      - "USE_JAEGER=1"
      - "DEBUG=1"
    volumes:
      - ".:/go/src/github.com/tinyci/ci-agents"
      - "./.ca:/var/ca"
      - "./.db:/var/lib/postgresql"
      - "./.logs:/var/tinyci/logs"
    links:
      - jaeger
    external_links:
      - react
